"""Consolidated formatters module for v0.1.9 simplification."""

from abc import ABC, abstractmethod
from typing import Dict, Any
import json
import datetime

# === BaseFormatter (from formatters/base.py) ===

class BaseFormatter(ABC):
    """Base interface for formatting architecture reports."""

    @abstractmethod
    def format(self, report: Dict[str, Any]) -> str:
        """Format the given report dictionary into a string."""
        pass

    def print(self, report: Dict[str, Any]):
        """Print the formatted report to stdout."""
        print(self.format(report))

# === JSONFormatter (from formatters/json.py) ===

class JSONFormatter(BaseFormatter):
    """Format the architecture report as a JSON string."""

    def __init__(self, indent: int = 2):
        self.indent = indent

    def format(self, report: Dict[str, Any]) -> str:
        return json.dumps(report, indent=self.indent)

# === MarkdownFormatter (from formatters/markdown.py) ===

class MarkdownFormatter(BaseFormatter):
    """Format the architecture report as a Markdown document."""

    def format(self, report: Dict[str, Any]) -> str:
        vibe_score = report.get('vibe_score', 0)
        stack = report.get('stack', 'unknown')
        files = report.get('files_analyzed', 0)
        total = report.get('total_lines', 0)

        now_utc = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
        timestamp = report.get('metadata', {}).get('timestamp', now_utc.isoformat() + "Z")

        if vibe_score >= 80:
            emoji = "🟢"
        elif vibe_score >= 60:
            emoji = "🟡"
        elif vibe_score >= 40:
            emoji = "🟠"
        else:
            emoji = "🔴"

        lines = [
            f"# Architecture Report — {timestamp}",
            "",
            f"## {emoji} Vibe Score: {vibe_score}/100",
            f"- **Stack**: {stack}",
            f"- **Files Analyzed**: {files}",
            f"- **Total Lines**: {total}",
        ]

        metrics = report.get('coupling_metrics', {})
        if metrics:
            avg_ccn = metrics.get('avg_ccn')
            avg_nd = metrics.get('avg_nd')
            if avg_ccn is not None or avg_nd is not None:
                lines.append(f"- **Avg CCN**: {avg_ccn or 'N/A'}")
                lines.append(f"- **Avg Nesting Depth**: {avg_nd or 'N/A'}")

        lines.append("")

        issues = report.get('issues', [])
        if issues:
            lines.append("## Issues Detected")
            for issue in issues:
                lines.append(f"- {issue}")
            lines.append("")

        ghosts = report.get('architectural_ghosts', [])
        if ghosts:
            lines.append("## 👻 Architectural Ghosts")
            for ghost in ghosts:
                lines.append(f"- {ghost}")
            lines.append("")

        flags = report.get('red_flags', [])
        if flags:
            lines.append("## 🚨 Red Flags")
            for flag in flags:
                lines.append(f"- {flag}")
            lines.append("")

        reasoning = report.get('ai_reasoning')
        if reasoning:
            lines.append("## AI Architect Reasoning")
            lines.append(reasoning)
            lines.append("")

        synthesis = report.get('ai_synthesis')
        if synthesis:
            lines.append("## ✨ AI Synthesis")
            lines.append(synthesis)
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Ghostclaw Architectural Assistant*")

        return "\n".join(lines)

# === TerminalFormatter (from formatters/terminal.py) ===

class TerminalFormatter(BaseFormatter):
    """Format the architecture report for terminal output."""

    def format(self, report: Dict[str, Any]) -> str:
        vibe_score = report.get('vibe_score', 0)
        stack = report.get('stack', 'unknown')
        files = report.get('files_analyzed', 0)
        total = report.get('total_lines', 0)

        if vibe_score >= 80:
            emoji = "🟢"
        elif vibe_score >= 60:
            emoji = "🟡"
        elif vibe_score >= 40:
            emoji = "🟠"
        else:
            emoji = "🔴"

        lines = [
            f"{emoji} Vibe Score: {vibe_score}/100",
            f"   Stack: {stack}",
            f"   Files: {files}, Lines: {total}"
        ]

        metrics = report.get('coupling_metrics', {})
        if metrics:
            avg_ccn = metrics.get('avg_ccn')
            avg_nd = metrics.get('avg_nd')
            if avg_ccn is not None or avg_nd is not None:
                lines.append(f"   Metrics: Avg CCN: {avg_ccn or 'N/A'}, Avg Nesting: {avg_nd or 'N/A'}")

        lines.append("")

        issues = report.get('issues', [])
        if issues:
            lines.append("Issues detected:")
            for issue in issues:
                lines.append(f"  • {issue}")
            lines.append("")

        ghosts = report.get('architectural_ghosts', [])
        if ghosts:
            lines.append("👻 Architectural Ghosts:")
            for ghost in ghosts:
                lines.append(f"   {ghost}")
            lines.append("")

        flags = report.get('red_flags', [])
        if flags:
            lines.append("🚨 Red Flags:")
            for flag in flags:
                lines.append(f"   {flag}")
            lines.append("")

        errors = report.get('errors', [])
        if errors:
            lines.append("⚠️ Adapter Errors:")
            for err in errors:
                lines.append(f"   {err}")
            lines.append("")

        lines.append("💡 Tip: Run with '--patch' to generate refactor suggestions")

        if "ai_synthesis" in report and not report.get("_synthesis_streamed", False):
            lines.append("\n✨ AI Synthesis:")
            if report.get("metadata", {}).get("cache_hit"):
                lines.append("(cached)")
            lines.append(report["ai_synthesis"])

        return "\n".join(lines)

    def print_to_terminal(self, report: Dict[str, Any]) -> None:
        """Print the formatted report to stdout."""
        print(self.format(report))

__all__ = ['BaseFormatter', 'JSONFormatter', 'MarkdownFormatter', 'TerminalFormatter']
