#!/usr/bin/env python3
"""
Ghostclaw CLI — command-line interface for the architectural analyzer.
"""

import sys
import json
import argparse
import subprocess
import datetime
from pathlib import Path
from typing import Dict, Optional

from dotenv import load_dotenv
from ghostclaw.core.analyzer import CodebaseAnalyzer
from ghostclaw.core.cache import LocalCache
from ghostclaw.core.config import GhostclawConfig
from ghostclaw.cli import __version__

try:
    from rich.console import Console
    from rich.markdown import Markdown
    from rich.status import Status
    HAS_RICH = True
except ImportError:
    HAS_RICH = False

load_dotenv()


def generate_markdown_report(report: Dict) -> str:
    """Generate Markdown content for the architectural report."""
    vibe_score = report['vibe_score']
    stack = report['stack']
    files = report['files_analyzed']
    total = report['total_lines']
    # Use timezone-aware UTC now, then format as ISO with Z suffix for consistency
    now_utc = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
    timestamp = report.get('metadata', {}).get('timestamp', now_utc.isoformat() + "Z")

    if vibe_score >= 80:
        emoji = "🟢"
    elif vibe_score >= 60:
        emoji = "🟡"
    elif vibe_score >= 40:
        emoji = "🟠"
    else:
        emoji = "🔴"

    lines = [
        f"# Architecture Report — {timestamp}",
        "",
        f"## {emoji} Vibe Score: {vibe_score}/100",
        f"- **Stack**: {stack}",
        f"- **Files Analyzed**: {files}",
        f"- **Total Lines**: {total}",
        ""
    ]

    issues = report.get('issues', [])
    if issues:
        lines.append("## Issues Detected")
        for issue in issues:
            lines.append(f"- {issue}")
        lines.append("")

    ghosts = report.get('architectural_ghosts', [])
    if ghosts:
        lines.append("## 👻 Architectural Ghosts")
        for ghost in ghosts:
            lines.append(f"- {ghost}")
        lines.append("")

    flags = report.get('red_flags', [])
    if flags:
        lines.append("## 🚨 Red Flags")
        for flag in flags:
            lines.append(f"- {flag}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Ghostclaw Architectural Assistant*")

    return "\n".join(lines)


def detect_github_remote(repo_path: str) -> Optional[str]:
    """Detect if the repository has a GitHub remote (origin)."""
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=False
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            if "github.com" in url:
                return url
    except Exception:
        pass
    return None


def create_github_pr(repo_path: str, report_file: Path, title: str, body: str):
    """Automate PR creation: branch, commit, push, gh pr create."""
    timestamp = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")
    branch_name = f"ghostclaw/arch-report-{timestamp}"

    try:
        # Create branch
        subprocess.run(["git", "checkout", "-b", branch_name], cwd=repo_path, check=True, capture_output=True, text=True)
        # Add report
        subprocess.run(["git", "add", report_file.name], cwd=repo_path, check=True, capture_output=True, text=True)
        # Commit
        subprocess.run(["git", "commit", "-m", f"Add architecture report: {report_file.name}"], cwd=repo_path, check=True, capture_output=True, text=True)
        # Push
        subprocess.run(["git", "push", "origin", branch_name], cwd=repo_path, check=True, capture_output=True, text=True)
        # Create PR
        pr_cmd = ["gh", "pr", "create", "--title", title, "--body", body]
        result = subprocess.run(pr_cmd, cwd=repo_path, capture_output=True, text=True, check=True)
        print(f"🔗 PR created: {result.stdout.strip()}")
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to create PR: {e.stderr or e}", file=sys.stderr)
    except Exception as e:
        print(f"❌ Error during PR creation: {str(e)}", file=sys.stderr)


def print_report(report: Dict):
    """Pretty-print the analysis report to terminal."""
    vibe_score = report['vibe_score']
    stack = report['stack']
    files = report['files_analyzed']
    total = report['total_lines']

    # Color/emoji based on vibe
    if vibe_score >= 80:
        emoji = "🟢"
    elif vibe_score >= 60:
        emoji = "🟡"
    elif vibe_score >= 40:
        emoji = "🟠"
    else:
        emoji = "🔴"

    print(f"{emoji} Vibe Score: {vibe_score}/100")
    print(f"   Stack: {stack}")
    print(f"   Files: {files}, Lines: {total}")
    print()

    issues = report.get('issues', [])
    if issues:
        print("Issues detected:")
        for issue in issues:
            print(f"  • {issue}")
        print()

    ghosts = report.get('architectural_ghosts', [])
    if ghosts:
        print("👻 Architectural Ghosts:")
        for ghost in ghosts:
            print(f"   {ghost}")
        print()

    flags = report.get('red_flags', [])
    if flags:
        print("🚨 Red Flags:")
        for flag in flags:
            print(f"   {flag}")
        print()

    print("💡 Tip: Run with '--patch' to generate refactor suggestions (not yet implemented)")

    if "ai_synthesis" in report:
        print("\n" + "="*50)
        print("🧠 Ghost Engine Synthesis (cached):\n")
        print(report["ai_synthesis"])
        print("\n" + "="*50)


def update_ghostclaw():
    """Perform self-update via pip or git."""
    print("🔄 Checking for Ghostclaw updates...")
    # Check if the package itself is in a git repo
    package_root = Path(__file__).parent.parent
    try:
        is_git = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            cwd=package_root,
            capture_output=True,
            text=True,
            check=False
        ).returncode == 0

        if is_git:
            print(f"Detected git repository at {package_root}. Pulling latest changes...")
            subprocess.run(["git", "pull"], cwd=package_root, check=True)
            print("✅ Updated via git.")
            # Also run pip install . to ensure dependencies are updated if pyproject.toml changed
            subprocess.run([sys.executable, "-m", "pip", "install", "-e", "."], cwd=package_root, check=True)
            return

    except Exception as e:
        print(f"⚠️ Git update failed or skipped: {e}")

    # Fallback to pip update
    try:
        print("Updating via pip...")
        subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", "ghostclaw"], check=True)
        print("✅ Updated via pip.")
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to update via pip: {e}", file=sys.stderr)
    except Exception as e:
        print(f"❌ Error during update: {e}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="Ghostclaw CLI — Architectural Analyzer")
    parser.add_argument("repo_path", nargs="?", help="Path to the repository to analyze")
    parser.add_argument("--version", action="version", version=f"Ghostclaw {__version__}")
    parser.add_argument("--update", action="store_true", help="Self-update Ghostclaw via pip or git")
    parser.add_argument("--json", action="store_true", help="Output raw JSON")
    parser.add_argument("--no-write-report", action="store_true", help="Skip writing the .md report file")
    parser.add_argument("--create-pr", action="store_true", help="Automatically create a GitHub PR with the report")
    parser.add_argument("--pr-title", help="Custom PR title")
    parser.add_argument("--pr-body", help="Custom PR body")

    # Caching options
    parser.add_argument("--no-cache", action="store_true", help="Disable result caching")
    parser.add_argument("--cache-dir", type=Path, help="Custom cache directory (default: ~/.cache/ghostclaw)")
    parser.add_argument("--cache-ttl", type=int, default=7, help="Cache TTL in days (default: 7)")
    parser.add_argument("--cache-stats", action="store_true", help="Show cache statistics after analysis")

    # AI options
    parser.add_argument("--use-ai", action="store_true", help="Enable Ghost Engine AI synthesis")
    parser.add_argument("--ai-provider", help="AI Provider (openrouter, openai, anthropic)")
    parser.add_argument("--dry-run", action="store_true", help="Dry run mode: prints prompt and token count without API call")
    parser.add_argument("--verbose", action="store_true", help="Verbose mode: saves raw API requests/responses to debug.log")

    # Engine Integrations (Phase 1)
    parser.add_argument("--pyscn", action="store_true", help="Enable PySCN integration")
    parser.add_argument("--no-pyscn", action="store_true", help="Explicitly disable PySCN integration")
    parser.add_argument("--ai-codeindex", action="store_true", help="Enable AI-CodeIndex integration")
    parser.add_argument("--no-ai-codeindex", action="store_true", help="Explicitly disable AI-CodeIndex integration")

    args = parser.parse_args()

    if args.update:
        update_ghostclaw()
        sys.exit(0)

    repo_path = args.repo_path
    if repo_path == "init":
        # Scaffold .ghostclaw.json template
        cwd = Path.cwd()
        gc_dir = cwd / ".ghostclaw"
        gc_dir.mkdir(parents=True, exist_ok=True)
        config_file = gc_dir / "ghostclaw.json"
        if config_file.exists():
            print(f"⚠️ {config_file} already exists. Skipping initialization.")
            sys.exit(0)

        template = {
            "use_ai": True,
            "ai_provider": "openrouter",
            "use_pyscn": False,
            "use_ai_codeindex": False
        }
        with open(config_file, "w", encoding="utf-8") as f:
            json.dump(template, f, indent=2)
        print(f"✅ Created template config at {config_file}")
        print("💡 Remember: Do NOT save your GHOSTCLAW_API_KEY in this file. Use an environment variable or ~/.ghostclaw/ghostclaw.json.")
        sys.exit(0)

    if not repo_path:
        parser.print_help()
        sys.exit(1)

    if not Path(repo_path).is_dir():
        print(f"Error: directory not found: {repo_path}", file=sys.stderr)
        sys.exit(1)

    # Initialize cache if enabled
    cache = None
    use_cache = not args.no_cache
    if use_cache:
        cache = LocalCache(cache_dir=args.cache_dir, ttl_days=args.cache_ttl)

    # Initialize Config
    # Extract known CLI overrides
    cli_overrides = {}
    if args.use_ai:
        cli_overrides['use_ai'] = True
    if args.ai_provider:
        cli_overrides['ai_provider'] = args.ai_provider
    if args.dry_run:
        cli_overrides['dry_run'] = True
    if args.verbose:
        cli_overrides['verbose'] = True

    # Handle backward compatibility flags
    if args.pyscn:
        cli_overrides['use_pyscn'] = True
    elif args.no_pyscn:
        cli_overrides['use_pyscn'] = False

    if args.ai_codeindex:
        cli_overrides['use_ai_codeindex'] = True
    elif args.no_ai_codeindex:
        cli_overrides['use_ai_codeindex'] = False

    try:
        config = GhostclawConfig.load(repo_path, **cli_overrides)
    except Exception as e:
        print(f"Configuration Error: {e}", file=sys.stderr)
        sys.exit(1)

    analyzer = CodebaseAnalyzer(cache=cache if use_cache else None)

    # The analyzer will handle its own rich terminal output for streaming AI synthesis
    report = analyzer.analyze(repo_path, use_cache=use_cache, config=config)

    # 1. Prepare and write report file if needed (must happen before stdout)
    report_file_path = None
    if not args.no_write_report:
        now = datetime.datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
        filename = f"ARCHITECTURE-REPORT-{now}.md"
        ghostclaw_dir = Path(repo_path) / ".ghostclaw"
        try:
            ghostclaw_dir.mkdir(parents=True, exist_ok=True)
            report_file_path = ghostclaw_dir / filename
            md_content = generate_markdown_report(report)
            report_file_path.write_text(md_content, encoding='utf-8')

            # Phase 0: Gitignore Injection
            gitignore_path = Path(repo_path) / ".gitignore"
            if gitignore_path.exists():
                content = gitignore_path.read_text(encoding='utf-8')
                if ".ghostclaw" not in content and ".ghostclaw/" not in content:
                    # Append it
                    newline = "\n" if not content.endswith("\n") else ""
                    with open(gitignore_path, "a", encoding="utf-8") as f:
                        f.write(f"{newline}# Added by Ghostclaw\n.ghostclaw/\n")
            else:
                # Optionally, we could create it, but usually we just warn or leave it alone.
                pass

        except Exception as e:
            print(f"Error writing report file or updating gitignore: {e}", file=sys.stderr)
            report_file_path = None

    # 2. Output to stdout
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print_report(report)

    # 3. Print confirmations and suggestions
    # Use stderr for these if --json is active, to keep stdout pipeable
    info_file = sys.stderr if args.json else sys.stdout

    if report_file_path:
        print(f"📝 Report written to: {report_file_path.absolute()}", file=info_file)

    remote_url = detect_github_remote(repo_path)
    if remote_url and not args.create_pr:
        print(f"💡 Tip: This repository has a GitHub remote.", file=info_file)
        print(f"   To create a PR with this report, run:", file=info_file)
        print(f"   ghostclaw \"{repo_path}\" --create-pr", file=info_file)

    # 4. Create PR if requested
    if args.create_pr:
        if not report_file_path:
            print("Error: Cannot create PR because report file was not written.", file=sys.stderr)
            return

        title = args.pr_title or f"🏰 Architecture Report - {datetime.datetime.now().strftime('%Y-%m-%d')}"
        body = args.pr_body or f"Ghostclaw has completed an architectural review of the codebase.\n\n**Vibe Score: {report['vibe_score']}/100**\n\nPlease review the attached report for details."
        create_github_pr(repo_path, report_file_path, title, body)

    # 5. Cache statistics if requested
    if args.cache_stats and cache:
        info = cache.info()
        stats_line = f"📊 Cache: {info['entries']} entries, {info['total_size_bytes']} bytes total ({info['cache_dir']})"
        print(stats_line, file=sys.stderr if args.json else sys.stdout)

    # If this was a cache hit, optionally indicate (not needed if --json but could still show in stderr)
    if not args.json and report.get('metadata', {}).get('cache_hit'):
        print("⚡ Cache hit!", file=sys.stderr)


if __name__ == "__main__":
    main()
