#!/usr/bin/env python3
"""
Ghostclaw CLI — command-line interface for the architectural analyzer.
"""

import sys
import json
import argparse
import subprocess
import datetime
from pathlib import Path
from typing import Dict, Optional

from dotenv import load_dotenv
from ghostclaw.core.analyzer import CodebaseAnalyzer
from ghostclaw.core.cache import LocalCache
from ghostclaw.core.config import GhostclawConfig
from ghostclaw.core.llm_client import LLMClient
from ghostclaw.core.agent import GhostAgent, AgentEvent
from ghostclaw.cli import __version__
import asyncio

try:
    from rich.console import Console
    from rich.markdown import Markdown
    from rich.status import Status
    from rich.text import Text
    HAS_RICH = True
except ImportError:
    HAS_RICH = False

load_dotenv()


def generate_markdown_report(report: Dict) -> str:
    """Generate Markdown content for the architectural report."""
    vibe_score = report['vibe_score']
    stack = report['stack']
    files = report['files_analyzed']
    total = report['total_lines']
    # Use timezone-aware UTC now, then format as ISO with Z suffix for consistency
    now_utc = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
    timestamp = report.get('metadata', {}).get('timestamp', now_utc.isoformat() + "Z")

    if vibe_score >= 80:
        emoji = "🟢"
    elif vibe_score >= 60:
        emoji = "🟡"
    elif vibe_score >= 40:
        emoji = "🟠"
    else:
        emoji = "🔴"

    lines = [
        f"# Architecture Report — {timestamp}",
        "",
        f"## {emoji} Vibe Score: {vibe_score}/100",
        f"- **Stack**: {stack}",
        f"- **Files Analyzed**: {files}",
        f"- **Total Lines**: {total}",
        ""
    ]

    issues = report.get('issues', [])
    if issues:
        lines.append("## Issues Detected")
        for issue in issues:
            lines.append(f"- {issue}")
        lines.append("")

    ghosts = report.get('architectural_ghosts', [])
    if ghosts:
        lines.append("## 👻 Architectural Ghosts")
        for ghost in ghosts:
            lines.append(f"- {ghost}")
        lines.append("")

    flags = report.get('red_flags', [])
    if flags:
        lines.append("## 🚨 Red Flags")
        for flag in flags:
            lines.append(f"- {flag}")
        lines.append("")

    reasoning = report.get('ai_reasoning')
    if reasoning:
        lines.append("## AI Architect Reasoning")
        lines.append(reasoning)
        lines.append("")

    synthesis = report.get('ai_synthesis')
    if synthesis:
        lines.append("## ✨ AI Synthesis")
        lines.append(synthesis)
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Ghostclaw Architectural Assistant*")

    return "\n".join(lines)


def detect_github_remote(repo_path: str) -> Optional[str]:
    """Detect if the repository has a GitHub remote (origin)."""
    try:
        result = subprocess.run(
            ["git", "remote", "get-url", "origin"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=False
        )
        if result.returncode == 0:
            url = result.stdout.strip()
            if "github.com" in url:
                return url
    except Exception:
        pass
    return None


def create_github_pr(repo_path: str, report_file: Path, title: str, body: str):
    """Automate PR creation: branch, commit, push, gh pr create."""
    timestamp = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")
    branch_name = f"ghostclaw/arch-report-{timestamp}"

    try:
        # Create branch
        subprocess.run(["git", "checkout", "-b", branch_name], cwd=repo_path, check=True, capture_output=True, text=True)
        # Add report with force (to bypass gitignore if needed)
        # Convert absolute report file path to relative path
        rel_report_path = report_file.relative_to(Path(repo_path))
        subprocess.run(["git", "add", "-f", str(rel_report_path)], cwd=repo_path, check=True, capture_output=True, text=True)
        # Commit
        subprocess.run(["git", "commit", "-m", f"Add architecture report: {report_file.name}"], cwd=repo_path, check=True, capture_output=True, text=True)
        # Push
        subprocess.run(["git", "push", "origin", branch_name], cwd=repo_path, check=True, capture_output=True, text=True)
        # Create PR
        pr_cmd = ["gh", "pr", "create", "--title", title, "--body", body]
        result = subprocess.run(pr_cmd, cwd=repo_path, capture_output=True, text=True, check=True)
        print(f"🔗 PR created: {result.stdout.strip()}")
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to create PR: {e.stderr or e}", file=sys.stderr)
    except Exception as e:
        print(f"❌ Error during PR creation: {str(e)}", file=sys.stderr)


def print_report(report: Dict):
    """Pretty-print the analysis report to terminal."""
    vibe_score = report['vibe_score']
    stack = report['stack']
    files = report['files_analyzed']
    total = report['total_lines']

    # Color/emoji based on vibe
    if vibe_score >= 80:
        emoji = "🟢"
    elif vibe_score >= 60:
        emoji = "🟡"
    elif vibe_score >= 40:
        emoji = "🟠"
    else:
        emoji = "🔴"

    print(f"{emoji} Vibe Score: {vibe_score}/100")
    print(f"   Stack: {stack}")
    print(f"   Files: {files}, Lines: {total}")
    print()

    issues = report.get('issues', [])
    if issues:
        print("Issues detected:")
        for issue in issues:
            print(f"  • {issue}")
        print()

    ghosts = report.get('architectural_ghosts', [])
    if ghosts:
        print("👻 Architectural Ghosts:")
        for ghost in ghosts:
            print(f"   {ghost}")
        print()

    flags = report.get('red_flags', [])
    if flags:
        print("🚨 Red Flags:")
        for flag in flags:
            print(f"   {flag}")
        print()

    errors = report.get('errors', [])
    if errors:
        print("⚠️ Adapter Errors:")
        for err in errors:
            print(f"   {err}")
        print()

    print("💡 Tip: Run with '--patch' to generate refactor suggestions")

    # Print AI synthesis if present and not already streamed (e.g., from cache)
    if "ai_synthesis" in report and not report.get("_synthesis_streamed", False):
        print("\n✨ AI Synthesis:")
        if report.get("metadata", {}).get("cache_hit"):
            print("(cached)")
        print(report["ai_synthesis"])


def update_ghostclaw():
    """Perform self-update via pip or git."""
    print("🔄 Checking for Ghostclaw updates...")
    # Check if the package itself is in a git repo
    package_root = Path(__file__).parent.parent
    try:
        is_git = subprocess.run(
            ["git", "rev-parse", "--is-inside-work-tree"],
            cwd=package_root,
            capture_output=True,
            text=True,
            check=False
        ).returncode == 0

        if is_git:
            print(f"Detected git repository at {package_root}. Pulling latest changes...")
            subprocess.run(["git", "pull"], cwd=package_root, check=True)
            print("✅ Updated via git.")
            # Also run pip install . to ensure dependencies are updated if pyproject.toml changed
            subprocess.run([sys.executable, "-m", "pip", "install", "-e", "."], cwd=package_root, check=True)
            return

    except Exception as e:
        print(f"⚠️ Git update failed or skipped: {e}")

    # Fallback to pip update
    try:
        print("Updating via pip...")
        subprocess.run([sys.executable, "-m", "pip", "install", "--upgrade", "ghostclaw"], check=True)
        print("✅ Updated via pip.")
    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to update via pip: {e}", file=sys.stderr)
    except Exception as e:
        print(f"❌ Error during update: {e}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description="Ghostclaw CLI — Architectural Analyzer")
    parser.add_argument("--version", action="version", version=f"Ghostclaw {__version__}")
    
    subparsers = parser.add_subparsers(dest="command", help="Sub-commands")

    # --- ANALYZE COMMAND ---
    analyze_parser = subparsers.add_parser("analyze", help="Analyze codebase architecture")
    analyze_parser.add_argument("repo_path", nargs="?", default=".", help="Path to the repository to analyze")
    analyze_parser.add_argument("--json", action="store_true", help="Output raw JSON")
    analyze_parser.add_argument("--no-write-report", action="store_true", help="Skip writing the .md report file")
    analyze_parser.add_argument("--create-pr", action="store_true", help="Automatically create a GitHub PR with the report")
    analyze_parser.add_argument("--pr-title", help="Custom PR title")
    analyze_parser.add_argument("--pr-body", help="Custom PR body")
    
    # Caching options
    analyze_parser.add_argument("--no-cache", action="store_true", help="Disable result caching")
    analyze_parser.add_argument("--cache-dir", type=Path, help="Custom cache directory (default: ~/.cache/ghostclaw)")
    analyze_parser.add_argument("--cache-ttl", type=int, default=7, help="Cache TTL in days (default: 7)")
    analyze_parser.add_argument("--cache-stats", action="store_true", help="Show cache statistics after analysis")

    # Parallel processing options
    analyze_parser.add_argument("--no-parallel", action="store_true", help="Disable parallel file scanning")
    analyze_parser.add_argument("--concurrency-limit", type=int, help="Max concurrent file operations (default: 32)")

    # AI options
    analyze_parser.add_argument("--use-ai", action="store_true", help="Enable Ghost Engine AI synthesis")
    analyze_parser.add_argument("--ai-provider", help="AI Provider (openrouter, openai, anthropic)")
    analyze_parser.add_argument("--ai-model", help="Specific LLM model to use")
    analyze_parser.add_argument("--dry-run", action="store_true", help="Dry run mode: prints prompt and token count without API call")
    analyze_parser.add_argument("--verbose", action="store_true", help="Verbose mode: saves raw API requests/responses to debug.log")
    analyze_parser.add_argument("--patch", action="store_true", help="Enable refactor plan/patch suggestions from the AI engine")

    # Engine Integrations
    analyze_parser.add_argument("--pyscn", action="store_true", help="Enable PySCN integration")
    analyze_parser.add_argument("--no-pyscn", action="store_true", help="Explicitly disable PySCN integration")
    analyze_parser.add_argument("--ai-codeindex", action="store_true", help="Enable AI-CodeIndex integration")
    analyze_parser.add_argument("--no-ai-codeindex", action="store_true", help="Explicitly disable AI-CodeIndex integration")

    # Reliability
    analyze_parser.add_argument("--strict", action="store_true", help="Treat adapter errors as fatal (non-zero exit)")

    # Observability
    analyze_parser.add_argument("--benchmark", action="store_true", help="Print performance timings after analysis")

    # --- INIT COMMAND ---
    init_parser = subparsers.add_parser("init", help="Scaffold local project configuration")

    # --- TEST COMMAND ---
    test_parser = subparsers.add_parser("test", help="Run diagnostic tests")
    test_parser.add_argument("--llm", action="store_true", help="Test LLM connectivity and list available models")
    test_parser.add_argument("--ai-provider", help="Provider to test (overrides config)")
    test_parser.add_argument("--ai-model", help="Model to test (overrides config)")

    # --- UPDATE COMMAND ---
    subparsers.add_parser("update", help="Self-update Ghostclaw via pip or git")

    # --- PLUGINS COMMAND ---
    plugins_parser = subparsers.add_parser("plugins", help="Manage architectural adapters/plugins")
    plugins_subparsers = plugins_parser.add_subparsers(dest="plugin_command", help="Plugin sub-commands")
    
    plugins_subparsers.add_parser("list", help="List all discovered plugins")
    
    info_parser = plugins_subparsers.add_parser("info", help="Show detailed info for a plugin")
    info_parser.add_argument("name", help="Name of the plugin")
    
    test_parser = plugins_subparsers.add_parser("test", help="Test if a plugin is available and working")
    test_parser.add_argument("name", help="Name of the plugin")

    add_parser = plugins_subparsers.add_parser("add", help="Install an external plugin from a local path")
    add_parser.add_argument("source", help="Path to the plugin directory or file")
    
    remove_parser = plugins_subparsers.add_parser("remove", help="Remove an external plugin")
    remove_parser.add_argument("name", help="Name of the plugin to remove")

    scaffold_parser = plugins_subparsers.add_parser("scaffold", help="Generate a boilerplate adapter")
    scaffold_parser.add_argument("name", help="Name of the new plugin")

    enable_parser = plugins_subparsers.add_parser("enable", help="Enable a plugin")
    enable_parser.add_argument("name", help="Name of the plugin to enable")

    disable_parser = plugins_subparsers.add_parser("disable", help="Disable a plugin")
    disable_parser.add_argument("name", help="Name of the plugin to disable")

    # Backward compatibility: if first arg is a directory, default to 'analyze'
    if len(sys.argv) > 1 and sys.argv[1] not in ["analyze", "init", "test", "update", "plugins", "-h", "--help", "--version"]:
        sys.argv.insert(1, "analyze")

    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    if args.command == "update":
        update_ghostclaw()
        sys.exit(0)


    if args.command == "plugins":
        import shutil
        from ghostclaw.core.adapters.registry import registry
        registry.register_internal_plugins()
        
        # Load external plugins from .ghostclaw/plugins if they exist
        local_plugins = Path.cwd() / ".ghostclaw" / "plugins"
        if local_plugins.exists():
            registry.load_external_plugins(local_plugins)

        if args.plugin_command == "list":
            metadata = registry.get_plugin_metadata()
            if not metadata:
                print("No plugins found.")
            else:
                from rich.table import Table
                table = Table(title="Ghostclaw Plugins")
                table.add_column("Name", style="cyan")
                table.add_column("Version", style="magenta")
                table.add_column("Description")
                table.add_column("Type", style="green")
                
                for meta in metadata:
                    name = meta.get("name", "unknown")
                    p_type = "Built-in" if name in registry.internal_plugins else "External"
                    table.add_row(
                        name,
                        meta.get("version", "unknown"),
                        meta.get("description", ""),
                        p_type
                    )
                
                if HAS_RICH:
                    Console().print(table)
                else:
                    print("Name | Version | Description | Type")
                    for meta in metadata:
                        name = meta.get("name")
                        p_type = "Built-in" if name in registry.internal_plugins else "External"
                        print(f"{name} | {meta.get('version')} | {meta.get('description')} | {p_type}")
        
        elif args.plugin_command == "add":
            source = Path(args.source)
            if not source.exists():
                print(f"❌ Source path '{source}' does not exist.", file=sys.stderr)
                sys.exit(1)
            
            dest_dir = Path.cwd() / ".ghostclaw" / "plugins"
            dest_dir.mkdir(parents=True, exist_ok=True)
            
            target = dest_dir / source.name
            if target.exists():
                print(f"⚠️ Plugin '{source.name}' already installed at {target}. Overwriting...")
                if target.is_dir(): shutil.rmtree(target)
                else: target.unlink()
            
            try:
                if source.is_dir():
                    shutil.copytree(source, target)
                else:
                    shutil.copy2(source, target)
                print(f"✅ Installed plugin '{source.name}' to {target}")
            except Exception as e:
                print(f"❌ Failed to install plugin: {e}", file=sys.stderr)
                sys.exit(1)

        elif args.plugin_command == "remove":
            name = args.name.lower()
            if name in registry.internal_plugins:
                print(f"🚫 Cannot remove built-in plugin '{name}'.", file=sys.stderr)
                sys.exit(1)
            
            # Look for it in .ghostclaw/plugins
            local_plugins_dir = Path.cwd() / ".ghostclaw" / "plugins"
            target = local_plugins_dir / name
            
            # Also check if they passed a name that matches a folder
            if not target.exists():
                # Search for any folder starting with 'name' (in case of dynamic suffixes)
                matches = list(local_plugins_dir.glob(f"{name}*"))
                if matches:
                    target = matches[0]
            
            if target.exists():
                try:
                    if target.is_dir(): shutil.rmtree(target)
                    else: target.unlink()
                    print(f"🗑️ Removed plugin '{name}' from {target}")
                except Exception as e:
                    print(f"❌ Failed to remove plugin: {e}", file=sys.stderr)
                    sys.exit(1)
            else:
                print(f"❌ External plugin '{name}' not found in {local_plugins_dir}.", file=sys.stderr)
                sys.exit(1)

        elif args.plugin_command == "info":
            # Finding the metadata for the specific plugin
            metadata = registry.get_plugin_metadata()
            plugin_meta = next((m for m in metadata if m.get("name") == args.name), None)
            if not plugin_meta:
                print(f"❌ Plugin '{args.name}' not found.", file=sys.stderr)
            else:
                print(f"Plugin: {plugin_meta.get('name')}")
                print(f"Version: {plugin_meta.get('version')}")
                print(f"Description: {plugin_meta.get('description')}")
        
        elif args.plugin_command == "enable":
            config_path = Path.cwd() / ".ghostclaw" / "ghostclaw.json"
            metadata = registry.get_plugin_metadata()
            all_names = [m.get("name") for m in metadata]
            if args.name not in all_names:
                print(f"❌ Plugin '{args.name}' not found. Available: {', '.join(all_names)}", file=sys.stderr)
                sys.exit(1)
            config_data = {}
            if config_path.exists():
                try:
                    config_data = json.loads(config_path.read_text())
                except Exception as e:
                    print(f"❌ Failed to read config: {e}", file=sys.stderr)
                    sys.exit(1)
            enabled = config_data.get("plugins_enabled")
            if enabled is None:
                # All enabled by default; nothing to do
                print(f"ℹ️ Plugin '{args.name}' is already enabled (all plugins enabled by default).")
                sys.exit(0)
            if args.name in enabled:
                print(f"ℹ️ Plugin '{args.name}' is already enabled.")
                sys.exit(0)
            enabled.append(args.name)
            config_data["plugins_enabled"] = enabled
            try:
                config_path.write_text(json.dumps(config_data, indent=2))
                print(f"✅ Enabled plugin '{args.name}'.")
            except Exception as e:
                print(f"❌ Failed to write config: {e}", file=sys.stderr)
                sys.exit(1)

        elif args.plugin_command == "disable":
            config_path = Path.cwd() / ".ghostclaw" / "ghostclaw.json"
            metadata = registry.get_plugin_metadata()
            all_names = [m.get("name") for m in metadata]
            if args.name not in all_names:
                print(f"❌ Plugin '{args.name}' not found. Available: {', '.join(all_names)}", file=sys.stderr)
                sys.exit(1)
            config_data = {}
            if config_path.exists():
                try:
                    config_data = json.loads(config_path.read_text())
                except Exception as e:
                    print(f"❌ Failed to read config: {e}", file=sys.stderr)
                    sys.exit(1)
            enabled = config_data.get("plugins_enabled")
            if enabled is None:
                # All enabled; create whitelist excluding this plugin
                enabled = [n for n in all_names if n != args.name]
                config_data["plugins_enabled"] = enabled
                try:
                    config_path.write_text(json.dumps(config_data, indent=2))
                    print(f"✅ Disabled plugin '{args.name}'. {len(enabled)} plugins remain enabled.")
                except Exception as e:
                    print(f"❌ Failed to write config: {e}", file=sys.stderr)
                    sys.exit(1)
            else:
                if args.name not in enabled:
                    print(f"ℹ️ Plugin '{args.name}' is already disabled (not in whitelist).")
                    sys.exit(0)
                enabled.remove(args.name)
                config_data["plugins_enabled"] = enabled
                try:
                    config_path.write_text(json.dumps(config_data, indent=2))
                    print(f"✅ Disabled plugin '{args.name}'.")
                except Exception as e:
                    print(f"❌ Failed to write config: {e}", file=sys.stderr)
                    sys.exit(1)

        elif args.plugin_command == "test":
            # Finding the instance and call is_available
            print(f"🧪 Testing plugin '{args.name}'...")
            metadata = registry.get_plugin_metadata()
            if any(m.get("name") == args.name for m in metadata):
                print(f"✅ Plugin '{args.name}' is registered.")
            else:
                print(f"❌ Plugin '{args.name}' is not registered.")
        
        elif args.plugin_command == "scaffold":
            name = args.name.lower().replace("-", "_")
            plugin_dir = Path.cwd() / ".ghostclaw" / "plugins" / name
            plugin_dir.mkdir(parents=True, exist_ok=True)
            
            init_file = plugin_dir / "__init__.py"
            if init_file.exists():
                print(f"⚠️ Plugin '{name}' already exists.")
            else:
                template = f'''"""
Ghostclaw Adapter: {name}
"""
from typing import Dict, List, Any, Optional
from ghostclaw.core.adapters.base import MetricAdapter, AdapterMetadata
from ghostclaw.core.adapters.hooks import hookimpl

class CustomAdapter(MetricAdapter):
    def get_metadata(self) -> AdapterMetadata:
        return AdapterMetadata(
            name="{name}",
            version="0.1.0",
            description="Custom architectural analysis.",
            dependencies=[]
        )

    async def is_available(self) -> bool:
        return True

    @hookimpl
    async def ghost_analyze(self, root: str, files: List[str]) -> Dict[str, Any]:
        return {{
            "issues": ["Example issue from {name}"],
            "architectural_ghosts": [],
            "red_flags": []
        }}

    @hookimpl
    def ghost_get_metadata(self) -> Dict[str, Any]:
        meta = self.get_metadata()
        return {{
            "name": meta.name,
            "version": meta.version,
            "description": meta.description
        }}
'''
                init_file.write_text(template)
                print(f"🏗️ Scaffolded plugin '{name}' at {plugin_dir}")
                print(f"💡 Edit {init_file} to add your logic.")
        
        sys.exit(0)

    if args.command == "init":
        cwd = Path.cwd()
        gc_dir = cwd / ".ghostclaw"
        gc_dir.mkdir(parents=True, exist_ok=True)
        config_file = gc_dir / "ghostclaw.json"
        if config_file.exists():
            print(f"⚠️ {config_file} already exists. Skipping initialization.")
            sys.exit(0)

        template = {
            "use_ai": True,
            "ai_provider": "openrouter",
            "ai_model": None,
            "use_pyscn": False,
            "use_ai_codeindex": False
        }
        with open(config_file, "w", encoding="utf-8") as f:
            json.dump(template, f, indent=2)
        print(f"✅ Created template config at {config_file}")
        print("💡 Remember: Do NOT save your GHOSTCLAW_API_KEY in this file. Use an environment variable or ~/.ghostclaw/ghostclaw.json.")
        sys.exit(0)

    if args.command == "test":
        if args.llm:
            async def _run_test():
                cli_overrides = {}
                if args.ai_provider: cli_overrides['ai_provider'] = args.ai_provider
                if args.ai_model: cli_overrides['ai_model'] = args.ai_model
                
                config = GhostclawConfig.load(".", **cli_overrides)
                client = LLMClient(config, ".")
                
                print(f"🔍 Testing LLM Connection ({config.ai_provider})...")
                success = await client.test_connection()
                if success:
                    print("✅ Connection successful!")
                    print("\nFetching available models...")
                    models = await client.list_models()
                    for m in models:
                        print(f"  • {m}")
                else:
                    print("❌ Connection failed. Check your API key and provider settings.")
            
            asyncio.run(_run_test())
        else:
            test_parser.print_help()
        sys.exit(0)

    if args.command == "analyze":
        repo_path = args.repo_path
        if not Path(repo_path).is_dir():
            print(f"Error: directory not found: {repo_path}", file=sys.stderr)
            sys.exit(1)

        # Determine cache usage
        use_cache = not args.no_cache

        # Initialize Config
        cli_overrides = {}
        if args.use_ai: cli_overrides['use_ai'] = True
        if args.ai_provider: cli_overrides['ai_provider'] = args.ai_provider
        if args.ai_model: cli_overrides['ai_model'] = args.ai_model
        if args.dry_run: cli_overrides['dry_run'] = True
        if args.verbose: cli_overrides['verbose'] = True
        if args.patch: cli_overrides['patch'] = True

        if args.pyscn: cli_overrides['use_pyscn'] = True
        elif args.no_pyscn: cli_overrides['use_pyscn'] = False

        if args.ai_codeindex: cli_overrides['use_ai_codeindex'] = True
        elif args.no_ai_codeindex: cli_overrides['use_ai_codeindex'] = False

        # Parallel processing overrides
        if args.no_parallel:
            cli_overrides['parallel_enabled'] = False
        if args.concurrency_limit is not None:
            cli_overrides['concurrency_limit'] = args.concurrency_limit

        try:
            config = GhostclawConfig.load(repo_path, **cli_overrides)
        except Exception as e:
            print(f"Configuration Error: {e}", file=sys.stderr)
            sys.exit(1)

        # Initialize cache if needed, with compression from config
        cache = None
        if use_cache:
            cache = LocalCache(
                cache_dir=args.cache_dir,
                ttl_days=args.cache_ttl,
                compression=config.cache_compression
            )

        analyzer = CodebaseAnalyzer(cache=cache if use_cache else None)
        agent = GhostAgent(config, repo_path, analyzer=analyzer)
        
        # Setup hooks for the CLI
        console = Console() if HAS_RICH and not args.json else None
        status = None
        live = None
        synthesis_content = []
        synthesis_streamed = False

        async def on_pre_analyze(data):
            nonlocal status
            if console:
                status = console.status("[bold green]Ghostclaw is analyzing architecture...[/bold green]", spinner="dots")
                status.start()

        async def on_post_metrics(data):
            nonlocal status
            if status:
                status.update("[bold blue]Metrics collected. Preparing Ghost Engine...[/bold blue]")

        async def on_pre_synthesis(data):
            nonlocal status
            if status:
                status.update("[bold cyan]🧠 Ghost Engine Synthesis starting...[/bold cyan]")
                print("\n" + "="*50 + "\n")
                print("🧠 Ghost Engine Synthesis:\n")

        async def on_synthesis_chunk(data):
            nonlocal status, live, synthesis_streamed
            synthesis_streamed = True
            chunk = data["chunk"]
            synthesis_content.append(chunk)
            
            if console:
                if status:
                    status.stop()
                    status = None
                
                if not live:
                    from rich.live import Live
                    live = Live(Text(""), console=console, refresh_per_second=10, transient=True)
                    live.start()
                
                live.update(Text("".join(synthesis_content)))
            else:
                output_stream = sys.stderr if args.json else sys.stdout
                output_stream.write(chunk)
                output_stream.flush()

        async def on_post_synthesis(data):
            nonlocal live, status
            if live:
                live.stop()
                live = None
            if status:
                status.stop()
                status = None
            
            output_stream = sys.stderr if args.json else sys.stdout
            output_stream.write("\n\n" + "="*50)
            output_stream.flush()
            if console and synthesis_content:
                full_text = "".join(synthesis_content)
                if full_text.strip(): console.print(Markdown(full_text))

        async def on_reasoning_chunk(data):
            nonlocal status, live
            chunk = data["chunk"]
            if console:
                if status:
                    status.stop()
                    status = None
                if not live:
                    from rich.live import Live
                    live = Live(Text(""), console=console, refresh_per_second=10, transient=True)
                    live.start()
                # Display reasoning in dimmed/italicized style
                current_text = live.get_renderable()
                if isinstance(current_text, Text):
                    current_text.append(chunk, style="dim italic")
                    live.update(current_text)
            else:
                output_stream = sys.stderr if args.json else sys.stdout
                output_stream.write(f"\033[2m{chunk}\033[0m")
                output_stream.flush()

        agent.on(AgentEvent.PRE_ANALYZE, on_pre_analyze)
        agent.on(AgentEvent.POST_METRICS, on_post_metrics)
        agent.on(AgentEvent.PRE_SYNTHESIS, on_pre_synthesis)
        agent.on(AgentEvent.REASONING_CHUNK, on_reasoning_chunk)
        agent.on(AgentEvent.SYNTHESIS_CHUNK, on_synthesis_chunk)
        agent.on(AgentEvent.POST_SYNTHESIS, on_post_synthesis)

        try:
            report = asyncio.run(agent.run())
            if args.benchmark:
                timings = getattr(agent, 'timings', {})
                if timings:
                    print("\n=== Benchmark Results (seconds) ===", file=sys.stderr)
                    for phase, duration in sorted(timings.items()):
                        print(f"{phase:20} {duration:>8.3f}s", file=sys.stderr)
                # Also show cache stats if used
                if use_cache and cache:
                    info = cache.info()
                    print(f"Cache entries: {info['entries']}, size: {info['total_size_bytes']} bytes", file=sys.stderr)
                report["_synthesis_streamed"] = synthesis_streamed
                # Update cache if post-synthesis (Agent handles synthesis internally now)
                if use_cache and cache and not config.dry_run and "metadata" in report and "fingerprint" in report["metadata"]:
                    cache.set(report["metadata"]["fingerprint"], report)
        except Exception as e:
            if status: status.stop()
            if live: live.stop()
            print(f"Analysis Error: {e}", file=sys.stderr)
            sys.exit(1)

        # Write Report
        report_file_path = None
        if not args.no_write_report:
            now = datetime.datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
            filename = f"ARCHITECTURE-REPORT-{now}.md"
            
            # For PR creation, write to repo root (outside .ghostclaw/) to avoid gitignore issues
            if args.create_pr:
                report_dir = Path(repo_path)
            else:
                report_dir = Path(repo_path) / ".ghostclaw"
                report_dir.mkdir(parents=True, exist_ok=True)
                # Add .ghostclaw to .gitignore if not already present (only for non-PR runs)
                gitignore_path = Path(repo_path) / ".gitignore"
                if gitignore_path.exists():
                    content = gitignore_path.read_text(encoding='utf-8')
                    if ".ghostclaw" not in content and ".ghostclaw/" not in content:
                        newline = "\n" if not content.endswith("\n") else ""
                        with open(gitignore_path, "a", encoding="utf-8") as f:
                            f.write(f"{newline}# Added by Ghostclaw\n.ghostclaw/\n")
            
            report_file_path = report_dir / filename
            try:
                report_file_path.write_text(generate_markdown_report(report), encoding='utf-8')
            except Exception as e:
                print(f"Error writing report: {e}", file=sys.stderr)

        # Output
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print_report(report)

        info_file = sys.stderr if args.json else sys.stdout
        if report_file_path:
            print(f"📝 Report written to: {report_file_path.absolute()}", file=info_file)

        remote_url = detect_github_remote(repo_path)
        if remote_url and not args.create_pr:
            print(f"💡 Tip: This repository has a GitHub remote.", file=info_file)
            print(f"   To create a PR with this report, run:", file=info_file)
            print(f"   ghostclaw analyze \"{repo_path}\" --create-pr", file=info_file)

        if args.create_pr:
            if not report_file_path:
                print("Error: Report file missing.", file=sys.stderr)
            else:
                title = args.pr_title or f"🏰 Architecture Report - {datetime.datetime.now().strftime('%Y-%m-%d')}"
                body = args.pr_body or f"Ghostclaw has completed an architectural review of the codebase.\n\n**Vibe Score: {report['vibe_score']}/100**\n\nPlease review the attached report for details."
                create_github_pr(repo_path, report_file_path, title, body)
                # Cleanup: remove the temporary PR report from repo root
                try:
                    report_file_path.unlink(missing_ok=True)
                except Exception as e:
                    print(f"Warning: could not delete temporary PR report: {e}", file=sys.stderr)

        if args.cache_stats and cache:
            info = cache.info()
            print(f"📊 Cache: {info['entries']} entries, {info['total_size_bytes']} bytes total ({info['cache_dir']})", file=info_file)

        if not args.json and report.get('metadata', {}).get('cache_hit'):
            print("⚡ Cache hit!", file=sys.stderr)

        # Strict mode: exit with non-zero if adapter errors occurred
        if args.strict and report.get('errors'):
            print(f"❌ {len(report['errors'])} adapter error(s) occurred (--strict). Exiting with failure.", file=sys.stderr)
            sys.exit(1)

if __name__ == "__main__":
    main()
