import datetime
from typing import Dict, Any
from ghostclaw.cli.formatters.base import BaseFormatter

class MarkdownFormatter(BaseFormatter):
    """
    Format the architecture report as a Markdown document.
    """

    def format(self, report: Dict[str, Any]) -> str:
        vibe_score = report.get('vibe_score', 0)
        stack = report.get('stack', 'unknown')
        files = report.get('files_analyzed', 0)
        total = report.get('total_lines', 0)

        # Use timezone-aware UTC now, then format as ISO with Z suffix for consistency
        now_utc = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
        timestamp = report.get('metadata', {}).get('timestamp', now_utc.isoformat() + "Z")

        if vibe_score >= 80:
            emoji = "🟢"
        elif vibe_score >= 60:
            emoji = "🟡"
        elif vibe_score >= 40:
            emoji = "🟠"
        else:
            emoji = "🔴"

        lines = [
            f"# Architecture Report — {timestamp}",
            "",
            f"## {emoji} Vibe Score: {vibe_score}/100",
            f"- **Stack**: {stack}",
            f"- **Files Analyzed**: {files}",
            f"- **Total Lines**: {total}",
        ]

        metrics = report.get('coupling_metrics', {})
        if metrics:
            avg_ccn = metrics.get('avg_ccn')
            avg_nd = metrics.get('avg_nd')
            if avg_ccn is not None or avg_nd is not None:
                lines.append(f"- **Avg CCN**: {avg_ccn if avg_ccn is not None else 'N/A'}")
                lines.append(f"- **Avg Nesting Depth**: {avg_nd if avg_nd is not None else 'N/A'}")

        lines.append("")

        issues = report.get('issues', [])
        if issues:
            lines.append("## Issues Detected")
            for issue in issues:
                lines.append(f"- {issue}")
            lines.append("")

        ghosts = report.get('architectural_ghosts', [])
        if ghosts:
            lines.append("## 👻 Architectural Ghosts")
            for ghost in ghosts:
                lines.append(f"- {ghost}")
            lines.append("")

        flags = report.get('red_flags', [])
        if flags:
            lines.append("## 🚨 Red Flags")
            for flag in flags:
                lines.append(f"- {flag}")
            lines.append("")

        reasoning = report.get('ai_reasoning')
        if reasoning:
            lines.append("## AI Architect Reasoning")
            lines.append(reasoning)
            lines.append("")

        synthesis = report.get('ai_synthesis')
        if synthesis:
            lines.append("## ✨ AI Synthesis")
            lines.append(synthesis)
            lines.append("")

        lines.append("---")
        lines.append("*Generated by Ghostclaw Architectural Assistant*")

        return "\n".join(lines)
